server {
    listen 8080;
    server_name localhost;
    root www/site1;
    index index.html;

    error_page 404 www/error_pages/404.html;
    error_page 500 www/error_pages/500.html;

    client_max_body_size 10M;

    location / {
        allowed_methods GET POST;
    }

    location /upload {
        allowed_methods POST DELETE;
        upload_path www/uploads;
    }

    location .php {
        cgi_pass /usr/bin/php-cgi;
    }
}
