server {
    listen localhost:8080;
    server_name localhost;

    root ./www;
    index site1/index.html;

    client_max_body_size 1000000;

    error_page 404 ./www/404.html;

    # location /jniji {
    #     allow_methods GET POST DELETE;
    #     autoindex off;

    # }
}
