events {}

http {
    error_log  /dev/stdout info;
    access_log /dev/stdout;

    server {
        listen 8080;
    	server_name localhost;
    	root /home/mait-you/Desktop/42_webserv/www/webserver-tester;
    	index index.html;
    	client_max_body_size 1000000;
    	location / {
    	    autoindex off;
    	}
    }
}
