events {}

http {
    error_log  /dev/stdout info;
    access_log /dev/stdout mylog;

    server {
        listen 8080;
        server_name localhost;

        location / {
            return 200 "HELLO\n";
        }
    }
}
